"""FabInventory Web Application

Blueprint architecture — see ``src/routes/__init__.py`` for the route map.
``src/core.py`` holds shared state, auth decorators, and config.
"""
import os
import secrets
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

# ── Auto-create .env if missing (fresh clone / first run) ──────
ENV_FILE = Path(__file__).resolve().parent.parent / ".env"

if not ENV_FILE.exists():
    ENV_FILE.write_text(
        "# Auto-generated by FabInventory on first run\n"
        f"SECRET_KEY={secrets.token_hex(32)}\n"
        "DATA_PATH=./fabinventory_data\n"
        "ADMIN_PASSWORD=fabinventory\n"
        "GITHUB_CLIENT_ID=\n"
        "GITHUB_CLIENT_SECRET=\n"
    )
    print(f"Created {ENV_FILE} with a generated SECRET_KEY.")

load_dotenv(ENV_FILE)

# ── Imports after env is loaded ────────────────────────────────
from flask import (
    Flask, render_template, request, jsonify, redirect, url_for,
    flash, Response, session, send_from_directory,
)
from flask_wtf.csrf import CSRFProtect

from src.core import state

# ── Flask setup ───────────────────────────────────────────────
app = Flask(
    __name__,
    static_folder='../static',
    template_folder='../templates',
)

secret_key = os.environ.get('SECRET_KEY')
if not secret_key:
    raise RuntimeError(
        "SECRET_KEY is required but could not be loaded. "
        "Check that your .env file exists and contains SECRET_KEY=..."
    )
app.secret_key = secret_key
app.config['UPLOAD_FOLDER'] = Path('static/uploads')
app.config['MAX_CONTENT_LENGTH'] = 500 * 1024 * 1024  # 500 MB
app.config['UPLOAD_FOLDER'].mkdir(parents=True, exist_ok=True)

import os as _os
_template_dir = _os.path.join(_os.path.dirname(_os.path.dirname(__file__)), 'templates')
app.template_folder = _template_dir

csrf = CSRFProtect(app)

# ── Public endpoints (no login required) ───────────────────────
_PUBLIC_ENDPOINTS = {
    'main.login',
    'main.login_github',
    'main.login_github_callback',
    'main.setup',
    'static',
}


@app.before_request
def _require_auth():
    """Require authentication for all pages except public endpoints."""
    if request.endpoint and request.endpoint not in _PUBLIC_ENDPOINTS:
        if not session.get('authenticated'):
            if request.path.startswith('/api/'):
                return jsonify({'error': 'Authentication required'}), 401
            flash('Please log in to continue.', 'warning')
            return redirect(url_for('main.login'))


# ── Context processor (Git status in navbar) ──────────────────
@app.context_processor
def inject_git_status():
    if state.initialized and state.git_manager:
        status = state.git_manager.get_status()
        status['commits_ahead'] = state.git_manager.commits_ahead()
        return {'git_status': status}
    return {'git_status': None}


# ── Register blueprints (at bottom to avoid circular import) ───
from src.routes.main import main_bp
from src.routes.projects import project_bp
from src.routes.inventory import inventory_bp
from src.routes.orders import orders_bp
from src.routes.api import api_bp
from src.routes.git_routes import git_bp

app.register_blueprint(main_bp)
app.register_blueprint(project_bp, url_prefix='/project')
app.register_blueprint(inventory_bp, url_prefix='/inventory')
app.register_blueprint(orders_bp)
app.register_blueprint(api_bp, url_prefix='/api')
app.register_blueprint(git_bp)


# ── Entry point ────────────────────────────────────────────────
def main():
    """Run the Flask application."""
    state.init_app()
    app.run(debug=True, host='0.0.0.0', port=9000)


if __name__ == '__main__':
    main()
